### ISSUE TITLE
gen_ops.py

### ISSUE THREAD

**Issue by LealemTilahun** [ag169/Image-Captioning#1]
am new to data science and getting lost here. when i tried to run it prints "'FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Python Projects\\Datasets\\MSRA10K_Imgs_GT\\GT\\76753.png'''. is MSRA10K a different dataset? what is the problem, or what should i do to make it run. am running it on ubuntu 21.10
![gen_ops](https://user-images.githubusercontent.com/66681406/139872800-ea7a17da-645c-45c2-9c99-3319fad3a647.png)
.

**Comment by ag169** [comment]
It's to test an image augmentation function. That augmentation is not used for image captioning.

**Comment by LealemTilahun** [comment]
Thanks a lot! please let me know which scripts are for image captioning and those for augumentation. my only focus is to study the concept of image captioning. and if its possible prepare your code for colab environment since my 8th gen i7 desktop with 16 GB ram takes forever for training

**Comment by ag169** [comment]
I haven't tried to run the code on colab yet. I'll update when that happens.
