### ISSUE TITLE
eval_caption.py

### ISSUE THREAD

**Issue by LealemTilahun** [ag169/Image-Captioning#2]
when i try to run eval_caption.py  script
![eval](https://user-images.githubusercontent.com/66681406/139872210-a8eedd76-587d-4f6d-9a08-1284c6de8e84.png)
prints the above message. thank you

**Comment by ag169** [comment]
--cdr needs to point to a checkpoint directory with a valid configuration and trained weights. Use train_caption.py to train your model.
