### ISSUE TITLE
train_caption.py

### ISSUE THREAD

**Issue by LealemTilahun** [ag169/Image-Captioning#3]
train_caption.py script can't run, here is the error message. thank you

![train_caption](https://user-images.githubusercontent.com/66681406/139873027-3682a151-9bdc-4b11-b0bf-95d2a1c8f5e3.png)

**Comment by ag169** [comment]
--cdr needs to point to a checkpoint directory with a valid configuration file. 

Calling
`python train_caption.py --cdr checkpoints/c1_r50_lstm`
should help you get started.

**Comment by LealemTilahun** [comment]
thanks a lot again.
