### ISSUE TITLE
asking for best trained model path

### ISSUE THREAD

**Issue by woynshetgebeyhu** [ag169/Image-Captioning#5]
first, i sincerly thank you for this project. i'am a newbee for Data Science and learning about Image captioning, and i find your code very intersting. so my question is if it's possible could you add a link to download latest trained model checkpoint file for all models. b/c it is very difficult to train deep learning models from scratch. so please add a link to download and play with it. thank you.

**Comment by ag169** [comment]
Sure. I intend to share the weight files and a script that can let you load an image and see the model's generated caption. 
I'm currently working on this codebase as part of a course project, so you'll have to wait around 2-3 weeks once the models are finalized.

**Comment by woynshetgebeyhu** [comment]
thank you.

**Comment by ag169** [comment]
Please check the latest commits.
